### ISSUE TITLE
Connections disappearing when zoom in Chrome

### ISSUE THREAD

**Issue by saracq** [retejs/rete#555] opened 2021-11-04 13:35 UTC
Since some days, I have problems with the rendering of connections in Chrome when my screen has a zoom of 125% (recommended by Windows). The connections are no longer centered in the sockets and, zooming rete container using the mouse wheel, some lines totally disappear.
This happens even in a particular environment, where the versions of rete libraries were set 6 months ago and where I'm sure this behaviour did not happen before, so I think that the cause is something relating to Chrome. Using Firefox all works fine indeed. You can see an example below with same zoom.
Chrome
![image](https://user-images.githubusercontent.com/8489445/140309819-a7d5e1a1-e74c-4b56-9c08-4aa4e9a5a01a.png)
Firefox
![image](https://user-images.githubusercontent.com/8489445/140309885-8bfd5062-4779-498d-a68f-734b3d517776.png)
The versions I use are the following
```javascript
{   
    ...,
    "nuxt": "^2.15.6",
    "rete": "^1.4.5-rc.1",
    "rete-area-plugin": "^0.2.1",
    "rete-connection-plugin": "^0.9.0",
    "rete-context-menu-plugin": "^0.6.0-rc.1",
    "rete-vue-render-plugin": "^0.5.1",
    ...,
}
```
Any ideas on how to solve this? Thanks!

**Comment by rvanasa** [comment] 2021-11-11 04:16
This happened to me as well. For whatever reason, it was caused by having duplicate element IDs somewhere else in the application. Try running `document.querySelectorAll('[id]')` to see if you accidentally assigned the same `id` attribute to two or more elements somewhere on the page.

**Comment by saracq** [comment] 2021-11-11 13:44
Hi @rvanasa, thanks for your suggestion! Unfortunately this not solve my problem, I don't have multiple elements with the same id on this page.

**Comment by Ni55aN** [comment] 2021-11-11 19:06
@saracq do you have a public example where it can be reproduced?

**Comment by rvanasa** [comment] 2021-11-19 03:12
This happened to me again for a different (unknown) reason, and I was able to fix it with the following CSS:

```css
.connection {
    position: static;
}
```

@saracq, hopefully this works for you in the short term. If static positioning doesn't break compatibility with other browsers, the problem could also be fixed by removing [this line in `src/view/connection.ts`](https://github.com/retejs/rete/blob/master/src/view/connection.ts#L20).

**Comment by saracq** [comment] 2021-11-19 11:59
@Ni55aN, sorry for the delay in replying. Unfortunatelly I don't have a public example, nevertheless the solution proposed by @rvanasa works for me! Thank you so much for your help @rvanasa :)

**Closed** 2021-11-19 13:00 UTC
